### PR TITLE
use java-headless instead of java

### PR DESCRIPTION
**Pull request by bentterp**
Should be a smaller install and more correct to use headless

### CODE REVIEW

**Comment by mglantz** [comment]
This is a very interesting pull request. Did you test this @bentterp ?
Also, allow me to include @jacobborella who is our middleware specialist. What do you think about this?

**Comment by bentterp** [comment]
[student@ip-172-31-23-60 work]$ grep java roles/wildflyapp/tasks/main.yml
- name: Install java
    name: java-headless
[student@ip-172-31-23-60 work]$

**Comment by bentterp** [comment]
wait and lemme try again after uninstalling java

**Comment by bentterp** [comment]
seem to work, I uninstalled java and java-headless on wildfly1
```
PLAY RECAP ***********************************************************************************************************
wildfly1                   : ok=8    changed=1    unreachable=0    failed=0
wildfly2                   : ok=8    changed=0    unreachable=0    failed=0

[student@ip-172-31-23-60 work]$ curl 52.208.71.138:8080
Howdy from unknown at 2018-09-05T11:01:55.987Z (from ip-172-31-17-214.eu-west-1.compute.internal)[student@ip-172-31-23[student@ip-172-31-23-60 work]$
```

**Comment by mglantz** [comment]
I've texted @jacobborella to help review. Seems like a solid change to me.

**Comment by jacobborella** [comment]
Good input. Since we have no GUI components (like Swing), I consider this an absolutely solid change.

**Comment by mglantz** [comment]
@jacobborella is this change the only thing needed to run it as headless?

**Comment by bentterp** [comment]
@mglantz no it's in more places, also in the lab I'm doing right now....

**Comment by mglantz** [comment]
@bentterp ping me know when you have added all needed change

**Comment by bentterp** [comment]
new PR which covers both lab 3 and 5, only places I've found it

**Comment by mglantz** [comment]
Excellent. I'm closing this one and merging the other.

**Pull request closed without merging**
