### PR TITLE
rename mypassword -> .mypassword to match the instructions in lab 5

### PR DESCRIPTION
**Pull request by nielsek**
The instructions says: `Do so by creating a file named .mypassword and put the password in the file.`

### CODE REVIEW

**Comment by mglantz** [comment]
Good catch, can you please make it mypassword instead of .mypassword. The reason for that is that there are people doing this lab who then will not understand that the file is not visible without doing _ls -l_.

**Comment by nielsek** [comment]
Sounds reasonable. Done :)

**Comment by mglantz** [comment]
Will be merged at lab completion 👍

**Comment by nielsek** [comment]
@mglantz when I win you can just send me the t shirt ;)

**Comment by mglantz** [comment]
Time for merge, again, thanks :)

**Pull request merged**
