### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Emil-G**
Why cut and paste all IP's another time?

### CODE REVIEW

**Comment by mglantz** [comment]
Makes sense, we're validating it

**Comment by idarlund** [comment]
It works, but you should add $WORK_DIR to the cat. that way it works from everywhere.
like this: cat $WORK_DIR/hosts | grep host | cut -d '=' -f 2 | xargs ssh-keyscan -H >> ~/.ssh/known_hosts

**Comment by mglantz** [comment]
Passed testing, merging this 👍

**Comment by mglantz** [comment]
> It works, but you should add $WORK_DIR to the cat. that way it works from everywhere.
> like this: cat $WORK_DIR/hosts | grep host | cut -d '=' -f 2 | xargs ssh-keyscan -H >> ~/.ssh/known_hosts

We talked about this and yes, that would be an additional improvement (even though the instruction before have you go to $WORK_DIR). Feel free to reopen and fix 👍

**Pull request merged**
